# Site settings
title: NamePuzzle
email: giveupyourdream@gmail.com
url: http://www.getnamepuzzle.com
description: "NamePuzzle for iPhone is an app to create and play your own personalized name puzzles!  Teach your child how to spell their name. Coming soon to the app store!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: New School Old School, LLC
  location: USA
  social: Around the Web
  credits: Site theme by Start Bootstrap

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'NamePuzzle is an app by <a href="http://www.newschoololdschool.com">New School Old School</a>.'

# Build settings
markdown: kramdown
permalink: pretty
